Add exemplar tags
hed-standard/hed-schemas pull request #256
Opened 2024-07-30 17:30 UTC by neuromechanist

I have added a couple of tags with references in the Annotation column.
I think there are some outstanding points:
1. Should the database names also defined in the prefixes (I assume not, because the names are already available in OBO)
2. Should we use `has_dbxref` or `db_xref` for cross-referencing (or any other label)? `has_dbxref` is defined [here](http://www.geneontology.org/formats/oboInOwl#dbxref) and `db_xref` is defined [here](https://www.ncbi.nlm.nih.gov/genbank/collab/db_xref/).
3. What should I do for the abbreviations, like `LHJ` and `RHJ`? Many of them are quite well-known and handy to use

2024-07-31 20:18 UTC, VisLab commented on library_schemas/slam/prerelease/hedtsv/HED_slam_1.0.0/HED_slam_1.0.0_Tag.tsv
> +	Acromion-process	2	Torso-chest-landmark		The outermost point of the shoulder blade.		has_dbxref: "NCIT:C32048" "FMA:12525" "UBERON:0002497"
The syntax here is incorrect.  Assuming that we were using obo: as the namespace prefix and `has_dbxref` as the AnnotationProperty, the syntax would be:

obo:has_dbxref  "NCIT:C32048",  obo:has_dbxref "FMA:12525", obo:has_dbxref  "UBERON:0002497"

However, we need to do some research on exactly what AnnotationProperty we want to use --- this is one that everyone will want to use.

2024-07-31 20:20 UTC, VisLab requested changes
This is a good first start. I am pretty sure that the links we will want to add will all be AnnotationProperty types (like has_dbxref) so we won't need any different infrastructure.

I have commented on the syntax problems above.  After we finalize exactly which thing we will use, this will just need the syntax corrected.

2024-07-31 21:53 UTC, neuromechanist commented
Thanks Kay,

I corrected the Annotations and added obo to the prefix table.

2024-08-01 10:29 UTC, VisLab commented on library_schemas/slam/prerelease/hedtsv/HED_slam_1.0.0/HED_slam_1.0.0_Prefixes.tsv
> +has_dbxref:	http://www.geneontology.org/formats/oboInOwl#dbxref	Relates an entity to an external database entry
The has_debxref should not be in the Prefixes file  it should be in the AnnotationsExternal file -- it is not a namespace, it is an AnnotationProperty.  Thus Line 12 should not be there -- However the obo ref should maybe be http://www.geneontology.org/formats/oboInOwl#.  Again, we will need to think about what property we want to use in general for this -- the `has_dbxref`  has a specific meaning.

2024-08-01 10:40 UTC, VisLab requested changes
There are some circular or incorrect references and other syntax errors:
- `Head-landmark` lists its parent as `Anatomical-landmarks`. It should be `Anatomical-landmark`
- `Torso-chest-landmark`  also lists `Anatomical-landmarks` as it parent.
- HED tag names cannot have blanks or parentheses. By convention only first letter is capitalized.
   - `Left-helix-tragus-junction`
   - `Right-helix-tragus-junction`
   - `Vertebra-promines`
   
 The stuff in parentheses should probably go in the description.

2024-08-01 16:56 UTC, neuromechanist commented
> There are some circular or incorrect references and other syntax errors:
> 
> * `Head-landmark` lists its parent as `Anatomical-landmarks`. It should be `Anatomical-landmark`
> * `Torso-chest-landmark`  also lists `Anatomical-landmarks` as it parent.
> * HED tag names cannot have blanks or parentheses. By convention only first letter is capitalized.
>   
>   * `Left-helix-tragus-junction`
>   * `Right-helix-tragus-junction`
>   * `Vertebra-promines`
> 
> The stuff in parentheses should probably go in the description.

Addressed!

2024-08-02 13:36 UTC, VisLab approved these changes

2024-08-02 13:37 UTC, merged